spring.datasource.url=jdbc:mysql://localhost:3306/ooad_cms
spring.datasource.username=root
spring.datasource.password=Spoorthi@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false